CREATE DATABASE IF NOT EXISTS aplikasi;

USE aplikasi;

CREATE TABLE IF NOT EXISTS pengguna (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    emel VARCHAR(100) NOT NULL,
    kata_laluan VARCHAR(100) NOT NULL
);